# ---------------------------------------------------------------------
# 0. Main options
# ---------------------------------------------------------------------
quant_tool: spectronaut           # choose between "diann" or "spectronaut"
spectronaut_activation_key: YOUR_KEY_HERE # Spectronaut activation key
spectronaut_direct_schema: "BGS Factory Settings"  # or path to .prop file if custom schema
spectronaut_report_schema: "BGS Factory Settings"  # or path to .prop file if custom schema
run_qc: false                # whether to run QC rules
batch_correction: false     # only set up for diann right now
run_mode: all            # options: cohort, workflow, all; default = all if blank

# ---------------------------------------------------------------------
# 1. Paths & metadata
# ---------------------------------------------------------------------
project_root: "/maps/projects/cbmr_fpm_soup-AUDIT/data/snakepro/"            # absolute or relative
metadata: "data_input/ms_raw_files.csv"       # metadata mapping raw files
project_name: "My_Project"                   # name of the project

# If you already have a fasta, provide its path (absolute or relative), e.g.:
# fasta: "data_input/human_swissprot_2025_07.fasta"
# Otherwise, set to the sentinel value below to fetch from UniProt:
fasta: "fetch_fasta"

# Parameters used when fasta == "fetch_fasta"
fasta_out_dir: "data_input"
organism_id: 9606         # 9606 (human), 10090 (mouse), etc.
reviewed: true            # Swiss-Prot only
include_isoforms: false    # true = canonical + isoforms, false = canonical only
exclude_fragments: true   # true = add 'fragment:false' to query
filename_prefix: "uniprot"  # optional: affects output name only

# ---------------------------------------------------------------------
# 2. Quality Control settings
# ---------------------------------------------------------------------
filtering_option: all      # "all" or "group"
group: null                # metadata group column name (if using group filtering)
filtering_percentage: 0.20 # e.g., remove if >20% missing
batch_column: "plate"      # metadata column name for batch grouping
missing_values_grouping: "condition"
pca_factors:
  - "plate"
  - "condition"
  - "time" # add more if you have in your metadata file or change to fit your needs
contamination_panel: false
contamination_panel_file: "data_input/contamination_panel.xlsx" # plasma specific contamination panel is already included
exclude_samples: []        # list of sample names to remove, e.g. ["s001", "s010"]

# adjust batch effect column here: ensure this is in metadata file 
batch_effect_column: "plate"

