# ---------------------------------------------------------------------
# 0. Main options
# ---------------------------------------------------------------------
quant_tool: diann           # choose between "diann" or "spectronaut"
run_qc: true                # whether to run QC rules
batch_correction: false     # only set up for diann right now
# ---------------------------------------------------------------------
# 1. Paths & metadata
# ---------------------------------------------------------------------
project_root: "/path/to/pipeline/"            # absolute or relative
metadata: "data_input/ms_raw_files.csv"       # metadata mapping raw files
fasta_file: "data_input/uniprot_reference.fa" # FASTA used for library or QC

# ---------------------------------------------------------------------
# 2. Quality Control settings
# ---------------------------------------------------------------------
filtering_option: all      # "all" or "group"
group: null                # metadata group column name (if using group filtering)
filtering_percentage: 0.20 # e.g., remove if >20% missing
batch_column: "plate"      # metadata column name for batch grouping
missing_values_grouping: "condition"
pca_factors:
  - "plate"
  - "condition"
  - "time" # add more if you have in your metadata file or change to fit your needs
contamination_panel: true
contamination_panel_file: "data_input/contamination_panel.xlsx"
exclude_samples: []        # list of sample names to remove, e.g. ["s001", "s010"]

# adjust batch effect column here: ensure this is in metadata file 
batch_effect_column: "plate"

